apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-weaviate
  labels:
    app: weaviate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weaviate
  template:
    metadata:
      labels:
        app: weaviate
    spec:
      containers:
        - name: weaviate
          image: "{{ .Values.weaviate.image.repository }}:{{ .Values.weaviate.image.tag }}"
          ports:
            - containerPort: {{ .Values.weaviate.service.port }}
            - containerPort: 2112  # Prometheus metrics port
          env:
            {{- range $key, $value := .Values.weaviate.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: weaviate-data
              mountPath: /var/lib/weaviate
      volumes:
        - name: weaviate-data
          {{- if .Values.weaviate.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-weaviate-pvc
          {{- else }}
          emptyDir: {}
          {{- end }} 