apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-weaviate
  labels:
    app: weaviate
spec:
  type: {{ .Values.weaviate.service.type }}
  ports:
    - port: {{ .Values.weaviate.service.port }}
      targetPort: {{ .Values.weaviate.service.port }}
      protocol: TCP
      name: http
    - port: 2112
      targetPort: 2112
      protocol: TCP
      name: metrics
  selector:
    app: weaviate 